{
  "SchemaVersion": 2,
  "CreatedAt": "2024-11-29T10:59:32.475930119+01:00",
  "ArtifactName": "/tmp/7af54f429a9c161382d6fdcb516d07cf984f92ef74caa02fddb218babeddd81d.sbom.json",
  "ArtifactType": "spdx",
  "Metadata": {
    "OS": {
      "Family": "ubuntu",
      "Name": "24.04"
    },
    "ImageConfig": {
      "architecture": "",
      "created": "0001-01-01T00:00:00Z",
      "os": "",
      "rootfs": {
        "type": "",
        "diff_ids": null
      },
      "config": {}
    }
  },
  "Results": [
    {
      "Target": "/tmp/7af54f429a9c161382d6fdcb516d07cf984f92ef74caa02fddb218babeddd81d.sbom.json (ubuntu 24.04)",
      "Class": "os-pkgs",
      "Type": "ubuntu",
      "Vulnerabilities": [
        {
          "VulnerabilityID": "CVE-2024-52533",
          "PkgID": "gir1.2-glib-2.0@2.80.0-6ubuntu3.1",
          "PkgName": "gir1.2-glib-2.0",
          "PkgIdentifier": {
            "PURL": "pkg:deb/ubuntu/gir1.2-glib-2.0@2.80.0-6ubuntu3.1?arch=amd64\u0026distro=ubuntu-24.04",
            "UID": "5fd82accd68bcdb4"
          },
          "InstalledVersion": "2.80.0-6ubuntu3.1",
          "FixedVersion": "2.80.0-6ubuntu3.2",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ubuntu",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-52533",
          "DataSource": {
            "ID": "ubuntu",
            "Name": "Ubuntu CVE Tracker",
            "URL": "https://git.launchpad.net/ubuntu-cve-tracker"
          },
          "Title": "glib: buffer overflow in set_connect_msg()",
          "Description": "gio/gsocks4aproxy.c in GNOME GLib before 2.82.1 has an off-by-one error and resultant buffer overflow because SOCKS4_CONN_MSG_LEN is not sufficient for a trailing '\\0' character.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-120"
          ],
          "VendorSeverity": {
            "azure": 4,
            "cbl-mariner": 4,
            "redhat": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:H",
              "V3Score": 7
            }
          },
          "References": [
            "http://www.openwall.com/lists/oss-security/2024/11/12/11",
            "https://access.redhat.com/security/cve/CVE-2024-52533",
            "https://gitlab.gnome.org/GNOME/glib/-/issues/3461",
            "https://gitlab.gnome.org/GNOME/glib/-/releases/2.82.1",
            "https://gitlab.gnome.org/Teams/Releng/security/-/wikis/home",
            "https://lists.debian.org/debian-lts-announce/2024/11/msg00020.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-52533",
            "https://ubuntu.com/security/notices/USN-7114-1",
            "https://www.cve.org/CVERecord?id=CVE-2024-52533"
          ],
          "PublishedDate": "2024-11-11T23:15:05.967Z",
          "LastModifiedDate": "2024-11-23T21:15:15.09Z"
        },
        {
          "VulnerabilityID": "CVE-2024-52533",
          "PkgID": "libglib2.0-0t64@2.80.0-6ubuntu3.1",
          "PkgName": "libglib2.0-0t64",
          "PkgIdentifier": {
            "PURL": "pkg:deb/ubuntu/libglib2.0-0t64@2.80.0-6ubuntu3.1?arch=amd64\u0026distro=ubuntu-24.04",
            "UID": "d9a815a913258909"
          },
          "InstalledVersion": "2.80.0-6ubuntu3.1",
          "FixedVersion": "2.80.0-6ubuntu3.2",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ubuntu",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-52533",
          "DataSource": {
            "ID": "ubuntu",
            "Name": "Ubuntu CVE Tracker",
            "URL": "https://git.launchpad.net/ubuntu-cve-tracker"
          },
          "Title": "glib: buffer overflow in set_connect_msg()",
          "Description": "gio/gsocks4aproxy.c in GNOME GLib before 2.82.1 has an off-by-one error and resultant buffer overflow because SOCKS4_CONN_MSG_LEN is not sufficient for a trailing '\\0' character.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-120"
          ],
          "VendorSeverity": {
            "azure": 4,
            "cbl-mariner": 4,
            "redhat": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:H",
              "V3Score": 7
            }
          },
          "References": [
            "http://www.openwall.com/lists/oss-security/2024/11/12/11",
            "https://access.redhat.com/security/cve/CVE-2024-52533",
            "https://gitlab.gnome.org/GNOME/glib/-/issues/3461",
            "https://gitlab.gnome.org/GNOME/glib/-/releases/2.82.1",
            "https://gitlab.gnome.org/Teams/Releng/security/-/wikis/home",
            "https://lists.debian.org/debian-lts-announce/2024/11/msg00020.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-52533",
            "https://ubuntu.com/security/notices/USN-7114-1",
            "https://www.cve.org/CVERecord?id=CVE-2024-52533"
          ],
          "PublishedDate": "2024-11-11T23:15:05.967Z",
          "LastModifiedDate": "2024-11-23T21:15:15.09Z"
        },
        {
          "VulnerabilityID": "CVE-2024-52533",
          "PkgID": "libglib2.0-data@2.80.0-6ubuntu3.1",
          "PkgName": "libglib2.0-data",
          "PkgIdentifier": {
            "PURL": "pkg:deb/ubuntu/libglib2.0-data@2.80.0-6ubuntu3.1?arch=all\u0026distro=ubuntu-24.04",
            "UID": "a6d03c55e1391b2b"
          },
          "InstalledVersion": "2.80.0-6ubuntu3.1",
          "FixedVersion": "2.80.0-6ubuntu3.2",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ubuntu",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-52533",
          "DataSource": {
            "ID": "ubuntu",
            "Name": "Ubuntu CVE Tracker",
            "URL": "https://git.launchpad.net/ubuntu-cve-tracker"
          },
          "Title": "glib: buffer overflow in set_connect_msg()",
          "Description": "gio/gsocks4aproxy.c in GNOME GLib before 2.82.1 has an off-by-one error and resultant buffer overflow because SOCKS4_CONN_MSG_LEN is not sufficient for a trailing '\\0' character.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-120"
          ],
          "VendorSeverity": {
            "azure": 4,
            "cbl-mariner": 4,
            "redhat": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:H",
              "V3Score": 7
            }
          },
          "References": [
            "http://www.openwall.com/lists/oss-security/2024/11/12/11",
            "https://access.redhat.com/security/cve/CVE-2024-52533",
            "https://gitlab.gnome.org/GNOME/glib/-/issues/3461",
            "https://gitlab.gnome.org/GNOME/glib/-/releases/2.82.1",
            "https://gitlab.gnome.org/Teams/Releng/security/-/wikis/home",
            "https://lists.debian.org/debian-lts-announce/2024/11/msg00020.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-52533",
            "https://ubuntu.com/security/notices/USN-7114-1",
            "https://www.cve.org/CVERecord?id=CVE-2024-52533"
          ],
          "PublishedDate": "2024-11-11T23:15:05.967Z",
          "LastModifiedDate": "2024-11-23T21:15:15.09Z"
        },
        {
          "VulnerabilityID": "CVE-2024-9287",
          "PkgID": "libpython3.12-minimal@3.12.3-1ubuntu0.2",
          "PkgName": "libpython3.12-minimal",
          "PkgIdentifier": {
            "PURL": "pkg:deb/ubuntu/libpython3.12-minimal@3.12.3-1ubuntu0.2?arch=amd64\u0026distro=ubuntu-24.04",
            "UID": "b37fdcabd8156ca5"
          },
          "InstalledVersion": "3.12.3-1ubuntu0.2",
          "FixedVersion": "3.12.3-1ubuntu0.3",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ubuntu",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-9287",
          "DataSource": {
            "ID": "ubuntu",
            "Name": "Ubuntu CVE Tracker",
            "URL": "https://git.launchpad.net/ubuntu-cve-tracker"
          },
          "Title": "python: Virtual environment (venv) activation scripts don't quote paths",
          "Description": "A vulnerability has been found in the CPython `venv` module and CLI where path names provided when creating a virtual environment were not quoted properly, allowing the creator to inject commands into virtual environment \"activation\" scripts (ie \"source venv/bin/activate\"). This means that attacker-controlled virtual environments are able to run commands when the virtual environment is activated. Virtual environments which are not created by an attacker or which aren't activated before being used (ie \"./venv/bin/python\") are not affected.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-428"
          ],
          "VendorSeverity": {
            "redhat": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:H/UI:R/S:C/C:L/I:H/A:N",
              "V3Score": 6.3
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2024-9287",
            "https://github.com/python/cpython/commit/633555735a023d3e4d92ba31da35b1205f9ecbd7",
            "https://github.com/python/cpython/commit/8450b2482586857d689b6658f08de9c8179af7db",
            "https://github.com/python/cpython/commit/9286ab3a107ea41bd3f3c3682ce2512692bdded8",
            "https://github.com/python/cpython/commit/ae961ae94bf19c8f8c7fbea3d1c25cc55ce8ae97",
            "https://github.com/python/cpython/commit/e52095a0c1005a87eed2276af7a1f2f66e2b6483",
            "https://github.com/python/cpython/issues/124651",
            "https://github.com/python/cpython/pull/124712",
            "https://github.com/python/cpython/pull/124712/commits/b6a3bbd155c558cdcda482629073e492437db3d0",
            "https://mail.python.org/archives/list/security-announce@python.org/thread/RSPJ2B5JL22FG3TKUJ7D7DQ4N5JRRBZL/",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-9287",
            "https://ubuntu.com/security/notices/USN-7116-1",
            "https://www.cve.org/CVERecord?id=CVE-2024-9287"
          ],
          "PublishedDate": "2024-10-22T17:15:06.697Z",
          "LastModifiedDate": "2024-11-04T18:15:05.627Z"
        },
        {
          "VulnerabilityID": "CVE-2024-9287",
          "PkgID": "libpython3.12-stdlib@3.12.3-1ubuntu0.2",
          "PkgName": "libpython3.12-stdlib",
          "PkgIdentifier": {
            "PURL": "pkg:deb/ubuntu/libpython3.12-stdlib@3.12.3-1ubuntu0.2?arch=amd64\u0026distro=ubuntu-24.04",
            "UID": "360187c832c5f8ca"
          },
          "InstalledVersion": "3.12.3-1ubuntu0.2",
          "FixedVersion": "3.12.3-1ubuntu0.3",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ubuntu",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-9287",
          "DataSource": {
            "ID": "ubuntu",
            "Name": "Ubuntu CVE Tracker",
            "URL": "https://git.launchpad.net/ubuntu-cve-tracker"
          },
          "Title": "python: Virtual environment (venv) activation scripts don't quote paths",
          "Description": "A vulnerability has been found in the CPython `venv` module and CLI where path names provided when creating a virtual environment were not quoted properly, allowing the creator to inject commands into virtual environment \"activation\" scripts (ie \"source venv/bin/activate\"). This means that attacker-controlled virtual environments are able to run commands when the virtual environment is activated. Virtual environments which are not created by an attacker or which aren't activated before being used (ie \"./venv/bin/python\") are not affected.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-428"
          ],
          "VendorSeverity": {
            "redhat": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:H/UI:R/S:C/C:L/I:H/A:N",
              "V3Score": 6.3
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2024-9287",
            "https://github.com/python/cpython/commit/633555735a023d3e4d92ba31da35b1205f9ecbd7",
            "https://github.com/python/cpython/commit/8450b2482586857d689b6658f08de9c8179af7db",
            "https://github.com/python/cpython/commit/9286ab3a107ea41bd3f3c3682ce2512692bdded8",
            "https://github.com/python/cpython/commit/ae961ae94bf19c8f8c7fbea3d1c25cc55ce8ae97",
            "https://github.com/python/cpython/commit/e52095a0c1005a87eed2276af7a1f2f66e2b6483",
            "https://github.com/python/cpython/issues/124651",
            "https://github.com/python/cpython/pull/124712",
            "https://github.com/python/cpython/pull/124712/commits/b6a3bbd155c558cdcda482629073e492437db3d0",
            "https://mail.python.org/archives/list/security-announce@python.org/thread/RSPJ2B5JL22FG3TKUJ7D7DQ4N5JRRBZL/",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-9287",
            "https://ubuntu.com/security/notices/USN-7116-1",
            "https://www.cve.org/CVERecord?id=CVE-2024-9287"
          ],
          "PublishedDate": "2024-10-22T17:15:06.697Z",
          "LastModifiedDate": "2024-11-04T18:15:05.627Z"
        },
        {
          "VulnerabilityID": "CVE-2024-9287",
          "PkgID": "libpython3.12t64@3.12.3-1ubuntu0.2",
          "PkgName": "libpython3.12t64",
          "PkgIdentifier": {
            "PURL": "pkg:deb/ubuntu/libpython3.12t64@3.12.3-1ubuntu0.2?arch=amd64\u0026distro=ubuntu-24.04",
            "UID": "23793527e241c5a1"
          },
          "InstalledVersion": "3.12.3-1ubuntu0.2",
          "FixedVersion": "3.12.3-1ubuntu0.3",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ubuntu",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-9287",
          "DataSource": {
            "ID": "ubuntu",
            "Name": "Ubuntu CVE Tracker",
            "URL": "https://git.launchpad.net/ubuntu-cve-tracker"
          },
          "Title": "python: Virtual environment (venv) activation scripts don't quote paths",
          "Description": "A vulnerability has been found in the CPython `venv` module and CLI where path names provided when creating a virtual environment were not quoted properly, allowing the creator to inject commands into virtual environment \"activation\" scripts (ie \"source venv/bin/activate\"). This means that attacker-controlled virtual environments are able to run commands when the virtual environment is activated. Virtual environments which are not created by an attacker or which aren't activated before being used (ie \"./venv/bin/python\") are not affected.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-428"
          ],
          "VendorSeverity": {
            "redhat": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:H/UI:R/S:C/C:L/I:H/A:N",
              "V3Score": 6.3
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2024-9287",
            "https://github.com/python/cpython/commit/633555735a023d3e4d92ba31da35b1205f9ecbd7",
            "https://github.com/python/cpython/commit/8450b2482586857d689b6658f08de9c8179af7db",
            "https://github.com/python/cpython/commit/9286ab3a107ea41bd3f3c3682ce2512692bdded8",
            "https://github.com/python/cpython/commit/ae961ae94bf19c8f8c7fbea3d1c25cc55ce8ae97",
            "https://github.com/python/cpython/commit/e52095a0c1005a87eed2276af7a1f2f66e2b6483",
            "https://github.com/python/cpython/issues/124651",
            "https://github.com/python/cpython/pull/124712",
            "https://github.com/python/cpython/pull/124712/commits/b6a3bbd155c558cdcda482629073e492437db3d0",
            "https://mail.python.org/archives/list/security-announce@python.org/thread/RSPJ2B5JL22FG3TKUJ7D7DQ4N5JRRBZL/",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-9287",
            "https://ubuntu.com/security/notices/USN-7116-1",
            "https://www.cve.org/CVERecord?id=CVE-2024-9287"
          ],
          "PublishedDate": "2024-10-22T17:15:06.697Z",
          "LastModifiedDate": "2024-11-04T18:15:05.627Z"
        },
        {
          "VulnerabilityID": "CVE-2024-9287",
          "PkgID": "python3.12@3.12.3-1ubuntu0.2",
          "PkgName": "python3.12",
          "PkgIdentifier": {
            "PURL": "pkg:deb/ubuntu/python3.12@3.12.3-1ubuntu0.2?arch=amd64\u0026distro=ubuntu-24.04",
            "UID": "59a3816c447f5725"
          },
          "InstalledVersion": "3.12.3-1ubuntu0.2",
          "FixedVersion": "3.12.3-1ubuntu0.3",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ubuntu",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-9287",
          "DataSource": {
            "ID": "ubuntu",
            "Name": "Ubuntu CVE Tracker",
            "URL": "https://git.launchpad.net/ubuntu-cve-tracker"
          },
          "Title": "python: Virtual environment (venv) activation scripts don't quote paths",
          "Description": "A vulnerability has been found in the CPython `venv` module and CLI where path names provided when creating a virtual environment were not quoted properly, allowing the creator to inject commands into virtual environment \"activation\" scripts (ie \"source venv/bin/activate\"). This means that attacker-controlled virtual environments are able to run commands when the virtual environment is activated. Virtual environments which are not created by an attacker or which aren't activated before being used (ie \"./venv/bin/python\") are not affected.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-428"
          ],
          "VendorSeverity": {
            "redhat": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:H/UI:R/S:C/C:L/I:H/A:N",
              "V3Score": 6.3
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2024-9287",
            "https://github.com/python/cpython/commit/633555735a023d3e4d92ba31da35b1205f9ecbd7",
            "https://github.com/python/cpython/commit/8450b2482586857d689b6658f08de9c8179af7db",
            "https://github.com/python/cpython/commit/9286ab3a107ea41bd3f3c3682ce2512692bdded8",
            "https://github.com/python/cpython/commit/ae961ae94bf19c8f8c7fbea3d1c25cc55ce8ae97",
            "https://github.com/python/cpython/commit/e52095a0c1005a87eed2276af7a1f2f66e2b6483",
            "https://github.com/python/cpython/issues/124651",
            "https://github.com/python/cpython/pull/124712",
            "https://github.com/python/cpython/pull/124712/commits/b6a3bbd155c558cdcda482629073e492437db3d0",
            "https://mail.python.org/archives/list/security-announce@python.org/thread/RSPJ2B5JL22FG3TKUJ7D7DQ4N5JRRBZL/",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-9287",
            "https://ubuntu.com/security/notices/USN-7116-1",
            "https://www.cve.org/CVERecord?id=CVE-2024-9287"
          ],
          "PublishedDate": "2024-10-22T17:15:06.697Z",
          "LastModifiedDate": "2024-11-04T18:15:05.627Z"
        },
        {
          "VulnerabilityID": "CVE-2024-9287",
          "PkgID": "python3.12-minimal@3.12.3-1ubuntu0.2",
          "PkgName": "python3.12-minimal",
          "PkgIdentifier": {
            "PURL": "pkg:deb/ubuntu/python3.12-minimal@3.12.3-1ubuntu0.2?arch=amd64\u0026distro=ubuntu-24.04",
            "UID": "d00be3b9a77f159a"
          },
          "InstalledVersion": "3.12.3-1ubuntu0.2",
          "FixedVersion": "3.12.3-1ubuntu0.3",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ubuntu",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-9287",
          "DataSource": {
            "ID": "ubuntu",
            "Name": "Ubuntu CVE Tracker",
            "URL": "https://git.launchpad.net/ubuntu-cve-tracker"
          },
          "Title": "python: Virtual environment (venv) activation scripts don't quote paths",
          "Description": "A vulnerability has been found in the CPython `venv` module and CLI where path names provided when creating a virtual environment were not quoted properly, allowing the creator to inject commands into virtual environment \"activation\" scripts (ie \"source venv/bin/activate\"). This means that attacker-controlled virtual environments are able to run commands when the virtual environment is activated. Virtual environments which are not created by an attacker or which aren't activated before being used (ie \"./venv/bin/python\") are not affected.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-428"
          ],
          "VendorSeverity": {
            "redhat": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:H/UI:R/S:C/C:L/I:H/A:N",
              "V3Score": 6.3
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2024-9287",
            "https://github.com/python/cpython/commit/633555735a023d3e4d92ba31da35b1205f9ecbd7",
            "https://github.com/python/cpython/commit/8450b2482586857d689b6658f08de9c8179af7db",
            "https://github.com/python/cpython/commit/9286ab3a107ea41bd3f3c3682ce2512692bdded8",
            "https://github.com/python/cpython/commit/ae961ae94bf19c8f8c7fbea3d1c25cc55ce8ae97",
            "https://github.com/python/cpython/commit/e52095a0c1005a87eed2276af7a1f2f66e2b6483",
            "https://github.com/python/cpython/issues/124651",
            "https://github.com/python/cpython/pull/124712",
            "https://github.com/python/cpython/pull/124712/commits/b6a3bbd155c558cdcda482629073e492437db3d0",
            "https://mail.python.org/archives/list/security-announce@python.org/thread/RSPJ2B5JL22FG3TKUJ7D7DQ4N5JRRBZL/",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-9287",
            "https://ubuntu.com/security/notices/USN-7116-1",
            "https://www.cve.org/CVERecord?id=CVE-2024-9287"
          ],
          "PublishedDate": "2024-10-22T17:15:06.697Z",
          "LastModifiedDate": "2024-11-04T18:15:05.627Z"
        },
        {
          "VulnerabilityID": "CVE-2024-47814",
          "PkgID": "vim@2:9.1.0016-1ubuntu7.3",
          "PkgName": "vim",
          "PkgIdentifier": {
            "PURL": "pkg:deb/ubuntu/vim@9.1.0016-1ubuntu7.3?arch=amd64\u0026distro=ubuntu-24.04\u0026epoch=2",
            "UID": "a2ae5b6df491202e"
          },
          "InstalledVersion": "2:9.1.0016-1ubuntu7.3",
          "FixedVersion": "2:9.1.0016-1ubuntu7.5",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ubuntu",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-47814",
          "DataSource": {
            "ID": "ubuntu",
            "Name": "Ubuntu CVE Tracker",
            "URL": "https://git.launchpad.net/ubuntu-cve-tracker"
          },
          "Title": "vim: use-after-free when closing buffers in Vim",
          "Description": "Vim is an open source, command line text editor. A use-after-free was found in Vim \u003c 9.1.0764. When closing a buffer (visible in a window) a BufWinLeave auto command can cause an use-after-free if this auto command happens to re-open the same buffer in a new split window. Impact is low since the user must have intentionally set up such a strange auto command and run some buffer unload commands. However this may lead to a crash. This issue has been addressed in version 9.1.0764 and all users are advised to upgrade. There are no known workarounds for this vulnerability.",
          "Severity": "LOW",
          "CweIDs": [
            "CWE-416"
          ],
          "VendorSeverity": {
            "amazon": 2,
            "azure": 1,
            "photon": 1,
            "redhat": 1,
            "ubuntu": 1
          },
          "CVSS": {
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:R/S:U/C:N/I:L/A:L",
              "V3Score": 3.9
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2024-47814",
            "https://github.com/vim/vim/commit/51b62387be93c65fa56bbabe1c3",
            "https://github.com/vim/vim/security/advisories/GHSA-rj48-v4mq-j4vg",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-47814",
            "https://ubuntu.com/security/notices/USN-7131-1",
            "https://www.cve.org/CVERecord?id=CVE-2024-47814"
          ],
          "PublishedDate": "2024-10-07T22:15:03.657Z",
          "LastModifiedDate": "2024-10-10T12:57:21.987Z"
        },
        {
          "VulnerabilityID": "CVE-2024-47814",
          "PkgID": "vim-common@2:9.1.0016-1ubuntu7.3",
          "PkgName": "vim-common",
          "PkgIdentifier": {
            "PURL": "pkg:deb/ubuntu/vim-common@9.1.0016-1ubuntu7.3?arch=all\u0026distro=ubuntu-24.04\u0026epoch=2",
            "UID": "be6664152e5c39fc"
          },
          "InstalledVersion": "2:9.1.0016-1ubuntu7.3",
          "FixedVersion": "2:9.1.0016-1ubuntu7.5",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ubuntu",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-47814",
          "DataSource": {
            "ID": "ubuntu",
            "Name": "Ubuntu CVE Tracker",
            "URL": "https://git.launchpad.net/ubuntu-cve-tracker"
          },
          "Title": "vim: use-after-free when closing buffers in Vim",
          "Description": "Vim is an open source, command line text editor. A use-after-free was found in Vim \u003c 9.1.0764. When closing a buffer (visible in a window) a BufWinLeave auto command can cause an use-after-free if this auto command happens to re-open the same buffer in a new split window. Impact is low since the user must have intentionally set up such a strange auto command and run some buffer unload commands. However this may lead to a crash. This issue has been addressed in version 9.1.0764 and all users are advised to upgrade. There are no known workarounds for this vulnerability.",
          "Severity": "LOW",
          "CweIDs": [
            "CWE-416"
          ],
          "VendorSeverity": {
            "amazon": 2,
            "azure": 1,
            "photon": 1,
            "redhat": 1,
            "ubuntu": 1
          },
          "CVSS": {
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:R/S:U/C:N/I:L/A:L",
              "V3Score": 3.9
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2024-47814",
            "https://github.com/vim/vim/commit/51b62387be93c65fa56bbabe1c3",
            "https://github.com/vim/vim/security/advisories/GHSA-rj48-v4mq-j4vg",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-47814",
            "https://ubuntu.com/security/notices/USN-7131-1",
            "https://www.cve.org/CVERecord?id=CVE-2024-47814"
          ],
          "PublishedDate": "2024-10-07T22:15:03.657Z",
          "LastModifiedDate": "2024-10-10T12:57:21.987Z"
        },
        {
          "VulnerabilityID": "CVE-2024-47814",
          "PkgID": "vim-runtime@2:9.1.0016-1ubuntu7.3",
          "PkgName": "vim-runtime",
          "PkgIdentifier": {
            "PURL": "pkg:deb/ubuntu/vim-runtime@9.1.0016-1ubuntu7.3?arch=all\u0026distro=ubuntu-24.04\u0026epoch=2",
            "UID": "907a873f8a5515f"
          },
          "InstalledVersion": "2:9.1.0016-1ubuntu7.3",
          "FixedVersion": "2:9.1.0016-1ubuntu7.5",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ubuntu",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-47814",
          "DataSource": {
            "ID": "ubuntu",
            "Name": "Ubuntu CVE Tracker",
            "URL": "https://git.launchpad.net/ubuntu-cve-tracker"
          },
          "Title": "vim: use-after-free when closing buffers in Vim",
          "Description": "Vim is an open source, command line text editor. A use-after-free was found in Vim \u003c 9.1.0764. When closing a buffer (visible in a window) a BufWinLeave auto command can cause an use-after-free if this auto command happens to re-open the same buffer in a new split window. Impact is low since the user must have intentionally set up such a strange auto command and run some buffer unload commands. However this may lead to a crash. This issue has been addressed in version 9.1.0764 and all users are advised to upgrade. There are no known workarounds for this vulnerability.",
          "Severity": "LOW",
          "CweIDs": [
            "CWE-416"
          ],
          "VendorSeverity": {
            "amazon": 2,
            "azure": 1,
            "photon": 1,
            "redhat": 1,
            "ubuntu": 1
          },
          "CVSS": {
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:R/S:U/C:N/I:L/A:L",
              "V3Score": 3.9
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2024-47814",
            "https://github.com/vim/vim/commit/51b62387be93c65fa56bbabe1c3",
            "https://github.com/vim/vim/security/advisories/GHSA-rj48-v4mq-j4vg",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-47814",
            "https://ubuntu.com/security/notices/USN-7131-1",
            "https://www.cve.org/CVERecord?id=CVE-2024-47814"
          ],
          "PublishedDate": "2024-10-07T22:15:03.657Z",
          "LastModifiedDate": "2024-10-10T12:57:21.987Z"
        },
        {
          "VulnerabilityID": "CVE-2024-47814",
          "PkgID": "xxd@2:9.1.0016-1ubuntu7.3",
          "PkgName": "xxd",
          "PkgIdentifier": {
            "PURL": "pkg:deb/ubuntu/xxd@9.1.0016-1ubuntu7.3?arch=amd64\u0026distro=ubuntu-24.04\u0026epoch=2",
            "UID": "5e2eff0a63a19b2"
          },
          "InstalledVersion": "2:9.1.0016-1ubuntu7.3",
          "FixedVersion": "2:9.1.0016-1ubuntu7.5",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ubuntu",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-47814",
          "DataSource": {
            "ID": "ubuntu",
            "Name": "Ubuntu CVE Tracker",
            "URL": "https://git.launchpad.net/ubuntu-cve-tracker"
          },
          "Title": "vim: use-after-free when closing buffers in Vim",
          "Description": "Vim is an open source, command line text editor. A use-after-free was found in Vim \u003c 9.1.0764. When closing a buffer (visible in a window) a BufWinLeave auto command can cause an use-after-free if this auto command happens to re-open the same buffer in a new split window. Impact is low since the user must have intentionally set up such a strange auto command and run some buffer unload commands. However this may lead to a crash. This issue has been addressed in version 9.1.0764 and all users are advised to upgrade. There are no known workarounds for this vulnerability.",
          "Severity": "LOW",
          "CweIDs": [
            "CWE-416"
          ],
          "VendorSeverity": {
            "amazon": 2,
            "azure": 1,
            "photon": 1,
            "redhat": 1,
            "ubuntu": 1
          },
          "CVSS": {
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:R/S:U/C:N/I:L/A:L",
              "V3Score": 3.9
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2024-47814",
            "https://github.com/vim/vim/commit/51b62387be93c65fa56bbabe1c3",
            "https://github.com/vim/vim/security/advisories/GHSA-rj48-v4mq-j4vg",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-47814",
            "https://ubuntu.com/security/notices/USN-7131-1",
            "https://www.cve.org/CVERecord?id=CVE-2024-47814"
          ],
          "PublishedDate": "2024-10-07T22:15:03.657Z",
          "LastModifiedDate": "2024-10-10T12:57:21.987Z"
        }
      ]
    }
  ]
}
